### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by weiweizhang6338** [hku-mars/multi_lidar_calib#1]
Do you have time to open source recently? Looking forward to your open source code.

**Comment by samsdolphin** [comment]
Hi, our code will be released in September. Sorry for the inconvenience.

**Comment by samsdolphin** [comment]
> Do you have time to open source recently? Looking forward to your open source code.

Hi, our code will be released in September. Sorry for the inconvenience.

**Comment by samsdolphin** [comment]
> Do you have time to open source recently? Looking forward to your open source code.

Hi, we have open-sourced our latest work, which is available at https://github.com/hku-mars/mlcc. And this repo will be closed.
